IF
  True()
THEN
  RESPONSE #100
    CutSceneId("tenya")
    setGlobal("B2#TenQuest","GLOBAL",9)
    ApplySpell(Myself,RESTORE_FULL_HEALTH)
    ApplySpell(Myself,WIZARD_FIRE_SHIELD_BLUE)
    Wait(3)
    ForceSpell("B2#LETHE",MEPHIT_ICE_SHARD)
    Wait(3)
    StartDialogueNoSet([PC])
END

IF
  True()
THEN
  RESPONSE #100
    CutSceneId("B2#LETHE")
    Wait(1)
    ForceSpell("tenya",MEPHIT_ICE_SHARD)
END

